export const API_URL = 'http://localhost:5000/graphql';

//login token
export const AUTH_TOKEN = 'auth-token'

//actions
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_REVIEW = 'ADD_REVIEW';
export const GET_REVIEWS = 'GET_REVIEWS';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const CLEAR_REVIEWS = 'CLEAR_REVIEWS';

export const ADD_PRODUCT_TO_SHOPPING_CART = 'ADD_PRODUCT_TO_SHOPPING_CART'
export const UPDATE_PRODUCT_NUMBER_IN_SHOPPING_CART = 'UPDATE_PRODUCT_NUMBER_IN_SHOPPING_CART' 
export const DELETE_PRODUCT_IN_SHOPPING_CART = 'DELETE_PRODUCT_IN_SHOPPING_CART' 
export const CLEAR_SHOPPING_CART = 'CLEAR_SHOPPING_CART'
export const REMOVE_PRODUCT_FROM_SHOPPING_CART = 'REMOVE_PRODUCT_FROM_SHOPPING_CART'
export const UPDATE_SHOPPING_CART_PRODUCT = 'UPDATE_SHOPPING_CART_PRODUCT'

export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAIL = 'AUTHENTICATE_USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'